# Exercici 1

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [13]:
import numpy as np

In [14]:
arr = np.array([3, 5, 6, 7, 8, 1, 6, 9, 2], dtype = np.int64)

In [15]:
print(arr.ndim)

1


In [16]:
print(arr.shape)

(9,)


# Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [17]:
print(arr.mean())

5.222222222222222


In [18]:
np.subtract(arr, arr.mean())

array([-2.22222222, -0.22222222,  0.77777778,  1.77777778,  2.77777778,
       -4.22222222,  0.77777778,  3.77777778, -3.22222222])

# Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [98]:
matriu = np.array([[3, 5, 6, 7, 4],
                  [8, 1, 6, 9, 2],
                  [2, 7, 1, 3, 4],
                  [3, 6, 4, 2, 7],
                  [6, 5, 3, 1, 8]])

array([4, 2, 4, 7, 8])

In [20]:
print(matriu.max())

9


In [21]:
print(matriu.max(axis = 1))

[7 9 7 7 8]


# Exercici 4

Mostreu-me amb exemples de diferents matrius, la **regla fonamental de Broadcasting** que diu: "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [33]:
a = np.random.random((3, 4))
b = np.ones((3, 4))
c = np.ones((1, 4))
d = np.random.random((3, 1))

[[0.41619169 0.36952617 0.86703907 0.66998103]
 [0.60222795 0.10941856 0.31094785 0.89963867]
 [0.31129678 0.10323025 0.76312123 0.37226328]]


In [23]:
a + b

array([[1.95246815, 1.41201607, 1.73657959, 1.27717783],
       [1.38421701, 1.01456639, 1.72753803, 1.13168779],
       [1.40748828, 1.72929737, 1.29348373, 1.82727106]])

In [24]:
a - d

array([[ 0.92489035,  0.38443826,  0.70900179,  0.24960002],
       [-0.16224693, -0.53189755,  0.1810741 , -0.41477615],
       [-0.12673655,  0.19507255, -0.2407411 ,  0.29304624]])

In [25]:
a * c

array([[0.95246815, 0.41201607, 0.73657959, 0.27717783],
       [0.38421701, 0.01456639, 0.72753803, 0.13168779],
       [0.40748828, 0.72929737, 0.29348373, 0.82727106]])

In [26]:
c / d

array([[36.26104412, 36.26104412, 36.26104412, 36.26104412],
       [ 1.82994693,  1.82994693,  1.82994693,  1.82994693],
       [ 1.87187109,  1.87187109,  1.87187109,  1.87187109]])

# Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [121]:
fila_1 = matriu[0, :]
print(fila_1)

[3 5 6 7 4]


In [122]:
columna_2 = matriu[:, 1]
print(columna_2)

[5 1 7 6 5]


In [123]:
fila_1 + columna_2

array([ 8,  6, 13, 13,  9])

# Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, **agafant cada element i comprovant si es divideix uniformement per quatre.**

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [43]:
import numpy.ma as ma 

In [51]:
mask = matriu % 4 == 0

In [52]:
mask

array([[False, False, False, False,  True],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False, False,  True]])

# Exercici 7

A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [55]:
matriu[mask]

array([4, 8, 4, 4, 8])

# Exercici 8

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. adoneu-vos que les imatges RGB (Red, Green, Blue) són realment 
només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8, 
manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.

Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.

In [76]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [77]:
img = mpimg.imread("pompompurin.jpg")

In [120]:
img_edit = img[:, :, 2] + img[:, :, 0]

In [132]:
mpimg.imsave("img_edit.jpg", img_edit)